/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JOptionPane;


/**
 *
 * @author Usuario
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        monedaBoton = new javax.swing.JButton();
        temperaturaBoton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        salir = new javax.swing.JButton();

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(177, 180, 195));

        monedaBoton.setBackground(new java.awt.Color(130, 128, 136));
        monedaBoton.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        monedaBoton.setForeground(new java.awt.Color(255, 255, 255));
        monedaBoton.setText("Monedas");
        monedaBoton.setAutoscrolls(true);
        monedaBoton.setBorderPainted(false);
        monedaBoton.setDefaultCapable(false);
        monedaBoton.setFocusPainted(false);
        monedaBoton.setFocusable(false);
        monedaBoton.setMaximumSize(new java.awt.Dimension(90, 24));
        monedaBoton.setMinimumSize(new java.awt.Dimension(90, 24));
        monedaBoton.setPreferredSize(new java.awt.Dimension(90, 24));
        monedaBoton.setRequestFocusEnabled(false);
        monedaBoton.setVerifyInputWhenFocusTarget(false);
        monedaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaBotonActionPerformed(evt);
            }
        });

        temperaturaBoton.setBackground(new java.awt.Color(130, 128, 136));
        temperaturaBoton.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        temperaturaBoton.setForeground(new java.awt.Color(255, 255, 255));
        temperaturaBoton.setText("Temperaturas");
        temperaturaBoton.setAutoscrolls(true);
        temperaturaBoton.setBorderPainted(false);
        temperaturaBoton.setFocusPainted(false);
        temperaturaBoton.setFocusable(false);
        temperaturaBoton.setRequestFocusEnabled(false);
        temperaturaBoton.setVerifyInputWhenFocusTarget(false);
        temperaturaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperaturaBotonActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Dubai Medium", 0, 36)); // NOI18N
        title.setText("¿Qué desea convertir?");

        salir.setBackground(new java.awt.Color(130, 128, 136));
        salir.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.setActionCommand("salir");
        salir.setAutoscrolls(true);
        salir.setBorderPainted(false);
        salir.setFocusPainted(false);
        salir.setFocusable(false);
        salir.setMaximumSize(new java.awt.Dimension(90, 24));
        salir.setMinimumSize(new java.awt.Dimension(90, 24));
        salir.setPreferredSize(new java.awt.Dimension(90, 24));
        salir.setRequestFocusEnabled(false);
        salir.setVerifyInputWhenFocusTarget(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(monedaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temperaturaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(monedaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temperaturaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void monedaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaBotonActionPerformed
        MonedaFrame convertorMonedas = new  MonedaFrame();
        convertorMonedas.setVisible(true);
        convertorMonedas.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_monedaBotonActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
    JOptionPane.showMessageDialog(null, "Saliendo del programa", "Aviso", HEIGHT);
	System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void temperaturaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperaturaBotonActionPerformed
        TemperaturaFrame convertorTemperatura = new TemperaturaFrame();
        convertorTemperatura.setVisible(true);
        convertorTemperatura.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_temperaturaBotonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton monedaBoton;
    private javax.swing.JButton salir;
    private javax.swing.JButton temperaturaBoton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
