/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import modelo.TemperaturaConversion;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class TemperaturaFrame extends javax.swing.JFrame {

    /**
     * Creates new form TemperaturaFrame
     */
    public TemperaturaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        temperaturaName = new javax.swing.JComboBox<>();
        temperaturaName2 = new javax.swing.JComboBox<>();
        cantidadGrados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        convertirTemperaturaBoton = new javax.swing.JButton();
        cancelarTemperaturaBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(177, 180, 195));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel1.setText("¿De qué unidad de medida?");

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel2.setText("¿A qué unidad de media?");

        temperaturaName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Celsius", "Kelvin" }));

        temperaturaName2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Celsius", "Kelvin" }));
        temperaturaName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperaturaName2ActionPerformed(evt);
            }
        });

        cantidadGrados.setBackground(new java.awt.Color(209, 217, 220));
        cantidadGrados.setForeground(new java.awt.Color(130, 128, 136));
        cantidadGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadGradosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel3.setText("Ingrese la cantidad a convertir:");

        convertirTemperaturaBoton.setBackground(new java.awt.Color(130, 128, 136));
        convertirTemperaturaBoton.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        convertirTemperaturaBoton.setForeground(new java.awt.Color(255, 255, 255));
        convertirTemperaturaBoton.setText("Convertir");
        convertirTemperaturaBoton.setAutoscrolls(true);
        convertirTemperaturaBoton.setBorderPainted(false);
        convertirTemperaturaBoton.setFocusPainted(false);
        convertirTemperaturaBoton.setRequestFocusEnabled(false);
        convertirTemperaturaBoton.setVerifyInputWhenFocusTarget(false);
        convertirTemperaturaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirTemperaturaBotonActionPerformed(evt);
            }
        });

        cancelarTemperaturaBoton.setBackground(new java.awt.Color(130, 128, 136));
        cancelarTemperaturaBoton.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        cancelarTemperaturaBoton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarTemperaturaBoton.setText("Cancelar");
        cancelarTemperaturaBoton.setAutoscrolls(true);
        cancelarTemperaturaBoton.setBorderPainted(false);
        cancelarTemperaturaBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelarTemperaturaBoton.setFocusPainted(false);
        cancelarTemperaturaBoton.setFocusable(false);
        cancelarTemperaturaBoton.setVerifyInputWhenFocusTarget(false);
        cancelarTemperaturaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarTemperaturaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelarTemperaturaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(convertirTemperaturaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(temperaturaName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(temperaturaName2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cantidadGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temperaturaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temperaturaName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(cantidadGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarTemperaturaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertirTemperaturaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadGradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadGradosActionPerformed

    private void convertirTemperaturaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirTemperaturaBotonActionPerformed
         String temperaturaOrigen = temperaturaName.getSelectedItem().toString();
    String temperaturaDestino = temperaturaName2.getSelectedItem().toString();
    String cantidad = cantidadGrados.getText().trim();

    if (cantidad.isEmpty() || !TemperaturaConversion.validarInput(cantidad)) {
        JOptionPane.showMessageDialog(null, "Los datos no son válidos. Por favor, introduzca solo números.");
        return;
    }

    double cantidadDouble = Double.parseDouble(cantidad);
    double resultado = TemperaturaConversion.obtenerFactorConversion(temperaturaOrigen, temperaturaDestino, cantidadDouble);

    JOptionPane.showMessageDialog(null, cantidad + " " + temperaturaOrigen + " son " + resultado + " " + temperaturaDestino);

    int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea hacer otra conversión?",
            "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

    if (confirmacion == 1 || confirmacion == 2) {
        JOptionPane.showMessageDialog(null, "Saliendo del programa");
        System.exit(0);
    }
    }//GEN-LAST:event_convertirTemperaturaBotonActionPerformed

    private void cancelarTemperaturaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarTemperaturaBotonActionPerformed
        Pantalla pantalla = new Pantalla();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_cancelarTemperaturaBotonActionPerformed

    private void temperaturaName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperaturaName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperaturaName2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarTemperaturaBoton;
    public static javax.swing.JTextField cantidadGrados;
    private javax.swing.JButton convertirTemperaturaBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> temperaturaName;
    private javax.swing.JComboBox<String> temperaturaName2;
    // End of variables declaration//GEN-END:variables
}
